### ISSUE TITLE
Zabbix and docker-compose: do not use IP addresses, but names

### ISSUE THREAD

**Issue by oli-arborum** [mpolinowski/mpolinowski.github.io#4]
When describing how to connect a zabbix-server with a zabbix-agent in a docker-compose environment you recommend determining the IP address of the zabbix-agent and enter it into the web GUI of the server, see https://mpolinowski.github.io/devnotes/2020-07-15--zabbix-docker-installation and https://mpolinowski.github.io/devnotes/2021-10-13--zabbix-compose-setup
However, IP addresses are not static in a docker environment. Thus, it makes more sense to address the agent by its host name (in docker equal to the container name): Just enter "zabbix-agent" in the "host name" field of the agent, clear the "IP address" field and switch "connect to" to "DNS". Now the configuration survives being restarted.

**Comment by mpolinowski** [comment]
Hi @oli-arborum,

it is true - once you start automating things on a Kubernetes scale you do depend on the Docker DNS service. I am not sure why, but I am still fond of using good old IPv4 addresses for everything smaller scale that is pretty static in nature. This is why I assign static IPs to every container and create separate networks for different applications:

```yml
networks:
  zbx_net_backend:
     ipv4_address: 172.16.239.106
     aliases:
      - zabbix-agent
      - zabbix-agent-passive
      - zabbix-agent-alpine
```

But you are right, I did add a line to the README file pointing out that you can use DNS instead:

https://github.com/mpolinowski/zabbix-server-compose
